apiVersion: gitops.kluctl.io/v1beta1
kind: KluctlDeployment
metadata:
  name: podinfo-test
  namespace: kluctl-system
spec:
  interval: 1m
  timeout: 2m
  source:
    url: https://github.com/codablock/kluctl-sessions-rawkode.git
    path: "apps/podinfo"
  target: prod
  context: default

  args:
    podinfo:
      replicas: 3

  prune: true
  delete: true
