



vars:
  - file: config/common.yaml
  # As you can see, we can also use templating here to dynamically load different files.
  - file: config/{{ args.env_type }}.yaml

deployments:
  - path: podinfo

commonLabels:
  podtato-head.kluctl.io/target: {{ target.name }}
  podtato-head.kluctl.io/env-type: {{ args.env_type }}
  podtato-head.kluctl.io/env-name: {{ args.env_name }}
